# Generated by Django 4.1.7 on 2023-04-30 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_rename_subscribers_category_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribe',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
